### ISSUE TITLE
Create an Iframe and insert a image  

### ISSUE THREAD

**Issue by Ameysurwase** [Google-DSC-DMCE/Portfolio-HacktoberFest-2023#10]
Integrate an iframe with the location of DMCE (Datta Meghe College of Engineering) into the 'Contact' section and insert a relevant image into the 'Education' section of a webpage for enhanced content and user experience

**Comment by Sagar007-Git** [comment]
hey @Ameysurwase !

this would be my first opensource contribution,

i would like to contribute to this issue , can you please assign this to me!?

**Comment by Ameysurwase** [comment]
Ya sure go ahead
