### ISSUE TITLE
Add a hover effect in blog section

### ISSUE THREAD

**Issue by Kartik0211** [Google-DSC-DMCE/Portfolio-HacktoberFest-2023#2]
add a on cursor hover effect or transition in all (6) given blogs in blog section

**Comment by Soham-Bharti** [comment]
Can I add hover effect as well as shadow and focus effect also?? Please give me a chance to participate in HacktoberFest 2023. Thanks

**Comment by Kartik0211** [comment]
> Can I add hover effect as well as shadow and focus effect also?? Please give me a chance to participate in HacktoberFest 2023. Thanks

Yes soham, you can add shadow and focus effect;  All the best

**Comment by karankoder** [comment]
Please assign me some issue @Kartik0211  @Google-DSC-DMCE

**Comment by Kartik0211** [comment]
> can you assign this to me.

yes you are assigned
