### ISSUE TITLE
create a footer

### ISSUE THREAD

**Issue by Kartik0211** [Google-DSC-DMCE/Portfolio-HacktoberFest-2023#3]
create a footer containing the text "powered by Google for Developers"  to enhance webpage branding with good css

**Comment by Soham-Bharti** [comment]
Hey can I do that?

**Comment by aks057** [comment]
can i do @Kartik0211 ?

**Comment by Kartik0211** [comment]
yes ypu can

**Comment by Kartik0211** [comment]
> can i do @Kartik0211 ?

yes you can

**Comment by Kartik0211** [comment]
> Hey can I do that?

sure, you are assigned

**Comment by ayusharma-20** [comment]
@Kartik0211 I have solved this issue. You can merge my Pull request or tell me some more changes to do ..

**Comment by AnnapurnaNeerukonda** [comment]
hey can you assign me this issue ..i would like to work on it ...i have one contribution left....hope i can do this
