### ISSUE TITLE
Create a Navigation bar

### ISSUE THREAD

**Issue by Kartik0211** [Google-DSC-DMCE/Portfolio-HacktoberFest-2023#4]
create a navigation bar(navbar) to enable users to navigate through the website's different section

**Comment by AmoghKharche** [comment]
Can you assign me this issue?

**Comment by Kartik0211** [comment]
> Can you assign me this issue?

you are assigned

**Comment by karankoder** [comment]
Can you assign me the issue? @Kartik0211
