### ISSUE TITLE
Add a suitable favcon 

### ISSUE THREAD

**Issue by Ameysurwase** [Google-DSC-DMCE/Portfolio-HacktoberFest-2023#5]
Incorporate a favicon,  to be displayed in a web browser's tab or bookmark list, enhancing brand recognition and visual appeal (use the logo image of favcon from the asset)

**Comment by Soham-Bharti** [comment]
Hey I can do that? I want to have my first contribution.

**Comment by Ameysurwase** [comment]
yes

**Comment by Soham-Bharti** [comment]
Assign me please then

**Comment by karankoder** [comment]
Can you assign me the issue?

**Comment by shivamshaw07** [comment]
I would like to work on it. Please the issue to me

**Comment by AnnapurnaNeerukonda** [comment]
hey can you assign me this issue ..i would like to work on it
