### ISSUE TITLE
change the color palette of the webpage

### ISSUE THREAD

**Issue by Kartik0211** [Google-DSC-DMCE/Portfolio-HacktoberFest-2023#8]
Modify the color palette of a website to achieve a different visual aesthetic or align with rebranding efforts.

**Comment by Sagar007-Git** [comment]
hey @Kartik0211 !

i would like to contribute to this issue.

i can make sure that, i can add great combination colors to look website aesthetic 

Can you please assign this issue to me!?

**Comment by Kartik0211** [comment]
yes, you can

**Comment by AnnapurnaNeerukonda** [comment]
hey can you assign me this issue ..i would like to work on it ...i have one contribution left....hope i can do this
